spring:
    application:
        name: persistence
    datasource:
        url: jdbc:p6spy:postgresql://localhost:5432/windwail

        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        username: windwail
        password: windwail
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
